name: Alice Blog Checker

on:
  # schedule:
  #   - cron: '*/30 * * * *' # 30分ごとに実行
  workflow_dispatch:

jobs:
  alice_blog_checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd packages/aliceBlogChecker
          npm install

      - name: Run Alice Blog Checker
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          ALICE_DISCORD_WEBHOOK_URL: ${{ secrets.ALICE_DISCORD_WEBHOOK_URL }}
          ERROR_WEBHOOK_URL: ${{ secrets.ERROR_WEBHOOK_URL }}
        run: |
          cd packages/aliceBlogChecker
          node index.js