name: Daily Update
on:
  schedule:
    - cron: '1 15 * * *' # UTCで15時1分(日本時間で0時1分)に実行
  workflow_dispatch:
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install moreutils and jq
        run: sudo apt-get update && sudo apt-get install -y moreutils jq
        
      - name: Update daily.json
        run: |
          # 日本時間で現在時刻を取得
          TODAY=$(TZ='Asia/Tokyo' date '+%Y/%m/%d %H:%M:%S')
          
          # GitHub APIを使用して当日のアクション実行結果を取得
          REPO="${GITHUB_REPOSITORY}"
          DATE=$(TZ='Asia/Tokyo' date '+%Y-%m-%d')
          ACTIONS_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${REPO}/actions/runs?created=${DATE}&per_page=100")
          
          # アクション名、成功回数、失敗回数、実行時間、請求対象時間を集計
          ACTIONS_SUMMARY=$(echo "$ACTIONS_DATA" | jq -r '
            .workflow_runs
            | group_by(.name)
            | map({
                action: .[0].name,
                success: map(select(.conclusion == "success")) | length,
                failure: map(select(.conclusion == "failure")) | length,
                duration: {
                  sum: ((map(if .run_duration_ms != null then .run_duration_ms else 0 end) | add) / 1000),
                  avg: ((map(if .run_duration_ms != null then .run_duration_ms else 0 end) | add) / (length * 1000))
                },
                billable: ((map(if .billable.UBUNTU.total_ms != null then .billable.UBUNTU.total_ms else 0 end) | add) / 60000)
              })
          ')
          
          # daily.jsonを更新
          jq --arg today "$TODAY" --argjson actions "$ACTIONS_SUMMARY" '
            .day = $today |
            .actions = $actions
          ' daily.json | sponge daily.json
        shell: bash
        
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add daily.json
          git commit -m 'Update daily.json'
        shell: bash
        
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'Update daily.json'
          branch: 'update-daily-json'
          base: 'main' 
          title: 'Automated PR for daily.json update'
          body: 'This PR is automatically created by GitHub Actions.'
          labels: 'automated-pr'
          merge: 'squash'
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          token: ${{ secrets.GH_TOKEN }}
