name: Daily Check

on:
  schedule:
    - cron: '0 15 * * *'  # 00:00 JST (15:00 UTC)
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Set timezone environment variable to JST
      run: |
        echo "TZ=Asia/Tokyo" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Check and update daily-check.json
      id: update-json
      run: |
        now=$(date --iso-8601=seconds)
        if [ ! -f daily-check.json ]; then
          echo '{"day": "'$now'", "error": 0}' > daily-check.json
        else
          error_count=$(gh issue list --state open | wc -l)
          jq --arg now "$now" --argjson error "$error_count" '.day = $now | .error = $error' daily-check.json > tmp.json && mv tmp.json daily-check.json
        fi
        echo "errors=$(jq '.error' daily-check.json)" >> $GITHUB_ENV

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git checkout -b update-daily-check
        git add daily-check.json
        git commit -m 'Update daily-check.json'
        git push -u origin update-daily-check
        gh pr create --title "Daily Check Update" --body "Auto-updated daily-check.json" --head update-daily-check --base main --repo clockcrockwork/cccDataImporter --token $GH_TOKEN

    - name: Merge Pull Request
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        pr_number=$(gh pr list --state open --head update-daily-check --json number --jq '.[0].number' --repo clockcrockwork/cccDataImporter --token $GH_TOKEN)
        gh pr merge $pr_number --merge --repo clockcrockwork/cccDataImporter --token $GH_TOKEN

    - name: Notify Discord if errors found
      if: ${{ env.errors != 0 }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"Open issues found: ${{ env.errors }}\"}" ${{ secrets.ERROR_DISCORD_WEBHOOK }}
