name: Fetch RSS Feeds

on:
  # schedule:
  #   - cron: '*/5 * * * *' # 5分ごとに実行
  workflow_dispatch:

jobs:
  fetch-rss-feeds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
  
    - name: Install libvips
      run: sudo apt-get install -y libvips

    - name: Set up environment variables
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
        echo "SUPABASE_FEED_TABLE_NAME=${{ secrets.SUPABASE_FEED_TABLE_NAME }}" >> $GITHUB_ENV
        echo "SUPABASE_FEED_TYPE_X=${{ secrets.SUPABASE_FEED_TYPE_X }}" >> $GITHUB_ENV
        echo "SUPABASE_STORAGE_BUCKET_NAME=${{ secrets.SUPABASE_STORAGE_BUCKET_NAME }}" >> $GITHUB_ENV
        echo "SUPABASE_STORAGE_FOLDER_NAME=${{ secrets.SUPABASE_STORAGE_FOLDER_NAME }}" >> $GITHUB_ENV
        echo "ERROR_WEBHOOK_URL=${{ secrets.ERROR_WEBHOOK_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_EMAIL=${{ secrets.SUPABASE_EMAIL }}" >> $GITHUB_ENV
        echo "SUPABASE_PASSWORD=${{ secrets.SUPABASE_PASSWORD }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        yarn install --ignore-optional
      working-directory: packages/fetchRss
    
    - name: Rebuild sharp
      run: |
        npx sharp-cli install --force
      working-directory: packages/fetchRss

    - name: Run Fetch RSS Feeds
      run: |
        node src/index.js
      working-directory: packages/fetchRss
